version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production 
      - DATABASE_URL=${EXTERNAL_DB_URL} # Agora usamos uma variável de ambiente
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    networks:
      - app-network

  frontend-admin:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - app-network

  frontend-cliente:
    build:
      context: ./frontend-cliente
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3002:80"
    environment:
      - VITE_API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge