version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DATABASE_URL=${DATABASE_PUBLIC_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - RAILS_STORAGE_SERVICE=amazon
    volumes:
      - ./logs:/rails/log
    networks:
      - app-network

  frontend-admin:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - app-network

  frontend-cliente:
    build:
      context: ./frontend-cliente
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3002:80"
    environment:
      - VITE_API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge