---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/produtos":
    get:
      summary: Lista produtos
      tags:
      - Produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    restaurante_id:
                      type: integer
                    descricao:
                      type: string
                    disponivel:
                      type: boolean
                    nome:
                      type: string
                    preco:
                      type: number
                  required:
                  - id
                  - restaurante_id
                  - descricao
                  - disponivel
                  - nome
                  - preco
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
