---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/produtos":
    get:
      summary: Lista produtos
      tags:
      - Produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    restaurante_id:
                      type: integer
                    descricao:
                      type: string
                    disponivel:
                      type: boolean
                    nome:
                      type: string
                    preco:
                      type: number
                  required:
                  - id
                  - restaurante_id
                  - descricao
                  - disponivel
                  - nome
                  - preco
  "/login":
    post:
      summary: "Login do usuário"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                    - email
                    - password
      responses:
        '200':
          description: "Token JWT retornado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - Bearer: []