development:
  adapter: postgresql
  channel_prefix: my_delivery_app_development

test:
  adapter: test

production:
  adapter: postgresql
  channel_prefix: my_delivery_app_production
  url: <%= ENV['DATABASE_URL'] %>
  allowed_request_origins: "*"