default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: daiana
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_delivery_app_dev

test:
  <<: *default
  database: my_delivery_app_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: my_delivery_app_prod_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_delivery_app_prod_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_delivery_app_prod_cable
    migrations_paths: db/cable_migrate